name = "PyPlotRecipes"
uuid = "f13a0356-cdf4-11e8-2897-c56ac0065663"
authors = ["Stefanos Carlström <stefanos.carlstrom@gmail.com>"]
version = "0.1.0"

[deps]
PyPlot = "d330b81b-6aea-500a-939a-2ce795aea3ee"
RecipesBase = "3cdcf5f2-1ef4-517c-9805-6587b60abb01"
